### ISSUE TITLE
Cider 2 Support?

### ISSUE THREAD

**Issue by kaer1a** [martinfekete10/Tuneful#96]
https://cider.sh
i favour Cider 2 over the Apple Music client so I was wondering if it's possible to support it?

**Comment by skyer1a** [comment]
they do have a REST/WS api, so that might help

**Comment by martinfekete10** [comment]
Correct me if I'm wrong, but it seems like Cider is a wrapper for Apple Music; Tuneful acts similarly, but calls system functions instead of Apple Music API (as I imagine Cider does) so I can't imagine a use case for this feature. Closing this issue but feel free to reopen if you have a specific use case in mind

**Comment by kaer1a** [comment]
Cider is a completely different Apple Music client and Tuneful can’t recognise Cider. It’s not a wrapper either They have a discord server.https://discord.gg/applemusicSent from my iPhoneOn 22 Sep 2024, at 3:14 pm, Martin Fekete ***@***.***> wrote:﻿
Correct me if I'm wrong, but it seems like Cider is a wrapper for Apple Music; Tuneful acts similarly, but calls system functions instead of Apple Music API (as I imagine Cider does) so I can't imagine a use case for this feature. Closing this issue but feel free to reopen if you have a specific use case in mind
